name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees:
  - tejus3131

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        Please provide as much detail as possible so it can be fixed quickly.

  - type: input
    id: command
    attributes:
      label: CLI command used
      description: The exact command you ran
      placeholder: create-agentverse-agent --default
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.12.1"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "Ubuntu 22.04 / macOS / Windows"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (if any)
      description: Paste logs here (run with --debug if applicable)
      render: shell

  - type: checkboxes
    id: confirmation
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues
          required: true
        - label: I am using the latest version
          required: true
